### ISSUE TITLE
NoClassDefFoundError: org/bstats/Metrics$CustomChart

### ISSUE THREAD

**Issue by mibby** [natrolite/vault#1]
Using release build. https://github.com/natrolite/vault/releases

```
[03:24:40] [Server thread/ERROR]: Could not load 'plugins\vault-1.6.1.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: org/bstats/Metrics$CustomChart
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[patched_1.12.jar:git-Paper-1143]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:328) ~[patched_1.12.jar:git-Paper-1143]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [patched_1.12.jar:git-Paper-1143]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:303) [patched_1.12.jar:git-Paper-1143]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:223) [patched_1.12.jar:git-Paper-1143]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:615) [patched_1.12.jar:git-Paper-1143]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
Caused by: java.lang.NoClassDefFoundError: org/bstats/Metrics$CustomChart
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_131]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_131]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:65) ~[patched_1.12.jar:git-Paper-1143]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:127) ~[patched_1.12.jar:git-Paper-1143]
	... 6 more
Caused by: java.lang.ClassNotFoundException: org.bstats.Metrics$CustomChart
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_131]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102) ~[patched_1.12.jar:git-Paper-1143]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[patched_1.12.jar:git-Paper-1143]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_131]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_131]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_131]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_131]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:65) ~[patched_1.12.jar:git-Paper-1143]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:127) ~[patched_1.12.jar:git-Paper-1143]
	... 6 more
```

**Comment by kanoxx** [comment]
You have to download the 'vault-1.6.1-shaded.jar'. 
Please use the [Spigot Downloads](https://www.spigotmc.org/resources/vault.41918/history) for Production.
