### ISSUE TITLE
Gringotts compatibility issue

### ISSUE THREAD

**Issue by LemADEC** [natrolite/vault#3]
As of Vault-1.6.1.jar and Gringotts-2.10-SNAPSHOT.jar, economy isn't working:
```
[13:16:04 ERROR]: Could not pass event PlayerCommandPreprocessEvent to boosCooldowns v3.8.5
org.bukkit.event.EventException
>       at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:338) ~[JavaPluginLoader$1.class:1.7.10-1614.57]
>       at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:1.7.10-1614.57]
>       at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) [SimplePluginManager.class:1.7.10-1614.57]
>       at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492) [SimplePluginManager.class:1.7.10-1614.57]
>       at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1348) [nh.class:?]
>       at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1107) [nh.class:?]
>       at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:38) [ir.class:?]
>       at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:53) [ir.class:?]
>       at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) [ej.class:?]
>       at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:181) [nc.class:?]
>       at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1023) [MinecraftServer.class:?]
>       at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432) [lt.class:?]
>       at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841) [MinecraftServer.class:?]
>       at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
>       at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]
Caused by: java.lang.NoSuchFieldError: accountHolderFactory
>       at net.milkbowl.vault.economy.plugins.Economy_Gringotts.getBalance(Economy_Gringotts.java:139) ~[?:?]
>       at net.milkbowl.vault.economy.plugins.Economy_Gringotts.has(Economy_Gringotts.java:149) ~[?:?]
>       at net.milkbowl.vault.economy.AbstractEconomy.has(AbstractEconomy.java:30) ~[?:?]
>       at cz.boosik.boosCooldown.BoosPriceManager.has(BoosPriceManager.java:113) ~[?:?]
>       at cz.boosik.boosCooldown.BoosCoolDownListener.checkRestrictions(BoosCoolDownListener.java:68) ~[?:?]
>       at cz.boosik.boosCooldown.BoosCoolDownListener.onPlayerCommandPreprocess(BoosCoolDownListener.java:241) ~[?:?]
>       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_141]
>       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_141]
>       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_141]
>       at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_141]
>       at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:334) ~[JavaPluginLoader$1.class:1.7.10-1614.57]
>       ... 14 more
...
[13:16:19 ERROR]: Command bal failed:
java.lang.NoSuchFieldError: accountHolderFactory
>       at net.milkbowl.vault.economy.plugins.Economy_Gringotts.hasAccount(Economy_Gringotts.java:129) ~[Vault-1.6.1.jar:?]
>       at com.earth2me.essentials.register.payment.methods.VaultEco.hasAccount(VaultEco.java:69) ~[EssentialsX-2.0.1%23468.jar:?]
>       at com.earth2me.essentials.User._getMoney(User.java:396) ~[EssentialsX-2.0.1%23468.jar:?]
>       at com.earth2me.essentials.User.getMoney(User.java:378) ~[EssentialsX-2.0.1%23468.jar:?]
>       at com.earth2me.essentials.commands.Commandbalance.run(Commandbalance.java:25) ~[EssentialsX-2.0.1%23468.jar:?]
>       at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:156) ~[EssentialsX-2.0.1%23468.jar:?]
>       at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:469) [EssentialsX-2.0.1%23468.jar:?]
>       at com.earth2me.essentials.Essentials.onCommand(Essentials.java:381) [EssentialsX-2.0.1%23468.jar:?]
>       at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [PluginCommand.class:1.7.10-1614.57]
>       at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) [SimpleCommandMap.class:1.7.10-1614.57]
>       at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:740) [CraftServer.class:1.7.10-1614.57]
>       at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchServerCommand(CraftServer.java:720) [CraftServer.class:1.7.10-1614.57]
>       at net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(DedicatedServer.java:474) [lt.class:?]
>       at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:433) [lt.class:?]
>       at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841) [MinecraftServer.class:?]
>       at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
>       at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]
```

**Comment by LemADEC** [comment]
Any idea how to fix this?

**Comment by Favorlock** [comment]
@LemADEC A field that is accessed by the Vault hook is no longer present in the Gringotts plugin. You would need to use a previous release that still works, otherwise you'll need to wait until support for the plugin is updated.

**Comment by LemADEC** [comment]
The latest compatible version is way too laggy to be considered.
